config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :users, only: [:new, :create]
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :body

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :body

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email, :password, :first_name, :last_name
  validates_uniqueness_of :email

  has_secure_password

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Post.find(params[:post_id]).comments.new(user_id: current_user.id)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
   user = User.new(user_params)
   if user.save
     session[:user_id] = user.id
     redirect_to root_path
   else
     render :new
   end
 end

 private
   def user_params
     params.require(:user).permit(:email, :password, :first_name, :last_name)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.erb
<%= form_for @comment do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :post_id %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="container m0 col-12">
      <div class="center">
        <h1 class="m0"> <%= link_to "The Blog", "/dashboard", class: "text-decoration-none black" %></h1>
      </div>
      <div class="mr1 right">
        <% if current_user %>
          <p><%= link_to 'log out', '/logout' %></p>
        <% else %>
          <p class="m0"><%= link_to 'sign up', new_user_path %></p>
          <p class="m0"><%= link_to 'sign in', '/login' %></p>
        <% end %>
      </div>
    </nav>

    <div class="">
      <%if current_user %>
        <h3>Welcome <%= current_user.first_name %></h3>
        <p><%= link_to 'New Post', new_post_path %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.erb
<%= render "form" %>

app/views/posts/new.erb
<%= render "form" %>

app/views/users/new.erb
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/welcome/index.erb
<div class="col-10 mx-auto">

  <h1 class="center">Blog Posts</h1>

  <div class="col-10 mx-auto">

    <% @posts.each do |post| %>
    <div class="border">
      <div class="ml1">
          <h3> <%= post.title %> </h3>
          <p> <%= post.body %> </p>
          <p> <%= post.user.first_name %> <%= post.user.last_name %> </p>
          <% if current_user && current_user.id == post.user.id %>
            <p> <%= link_to 'Edit', edit_post_path(post) %> </p>
            <p> <%= link_to 'Delete', post_path(post), method: :delete %> </p>
          <% end %>
          <h5>Comments</h5>
          <% post.comments.each do |comment| %>
            <p> <%= comment.body %> </p>
            <p> - <%= comment.user.first_name %></p>
          <% end %>
          <% if current_user %>
            <p> <%= link_to 'Comment', new_comment_path(post_id: post.id) %> </p>
          <% else %>
            <p>log in to comment!</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>